[build]
  command = ""
  publish = "/"

[dev]
  command = "npm run build"
  targetPort = 8000

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    fail_deploy_on_score_thresholds = true
    [plugins.inputs.thresholds]
      accessibility = 0.98
      best-practices = 0.92
      seo = 0.98