backend:
  name: github
  repo: hjhgitw/GeoService-Website
  branch: main
  auth:
    client_id: Ov23liYIvCsznuR8HoHR
    redirect_uri: https://geoservice.netlify.app/callback

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "public"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }